baseURL: "https://akuls.com/"
languageCode: "en-us"
title: "Akul Santhosh"
theme: "hugo-PaperMod"

params:
    homeInfoParams:
        Picture: "dp.JPG"
        Title: Hi I'm Akul Santhosh.
        Content: I'm a Masters' student in Computer Science studying at NYU Courant.
    
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true

    # socialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"

    ShowShareButtons: true
    custom_css: ["changes.css"]

menu:
    main:
        - identifier: about
          name: About
          url: /about/
        - identifier: posts
          name: Posts
          url: /posts/
        - identifier: projects
          name: Projects
          url: /projects/

