baseURL: "https://akuls.com/"
languageCode: "en-us"
title: "Akul Santhosh"
theme: "hugo-PaperMod"

params:
    homeInfoParams:
        Picture: "dp.JPG"
        Title: Hi I'm Akul Santhosh.
        Content: I'm a Masters' student in Computer Science studying at NYU Courant.

    # socialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"

    ShowShareButtons: true

    custom_css: ["changes.css"]